### ISSUE TITLE
Website no longer loads

### ISSUE THREAD

**Issue by tapir132** [25Karma/25Karma#16]
As of a few hours ago, 25karma no longer loads. I believe this may be because of the recent changes to how API keys work, where you now have to make an app. Here is the link for that if you need it  https://developer.hypixel.net/ and here is the forum post that explains it https://hypixel.net/threads/hypixel-developer-dashboard-public-api-changes-june-2023.5364455/

**Comment by amosyu2000** [comment]
Thanks, this has been fixed.
