### ISSUE TITLE
25karma.github.io won't redirect

### ISSUE THREAD

**Issue by TheGalacticAce** [25Karma/25Karma#9]
When you go to 25karma.github.io it won't redirect us to 25karma.xyz as usual

![image](https://user-images.githubusercontent.com/72170182/116352652-53f86a00-a7aa-11eb-9c52-42e2b42c7d65.png)

**Comment by amosyu2000** [comment]
Yes, this is intended behavior. 25karma.github.io is now deprecated. Please navigate to 25karma.xyz from now on.
